from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON = FILES_DIR / 'icon.png'

MAX_FONT_SIZE = 40
MED_FONT_SIZE = 30
MIN_FONT_SIZE = 20
DEFAULT_STRING_MARGIN = 10
MIN_WIDGET_WIDTH = 500

PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'